[package]
name = "pqo-vulkan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ash = "0.38"
pqo-cuda = { path = "../pqo-cuda" }
serde.workspace = true
serde_json.workspace = true
raw-window-handle = "0.5"
winit = "0.28"

[lib]
path = "src/lib.rs"

[[example]]
name = "probe"
path = "examples/probe.rs"

[[example]]
name = "window"
path = "examples/window.rs"
