[package]
name = "loom-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
loom-core = { path = "../loom-core" }
loom-syntax = { path = "../loom-syntax" }
loom-validator = { path = "../loom-validator" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
loom-metal = { path = "../loom-metal" }

[[bin]]
name = "loom"
path = "src/main.rs"
