[package]
name = "loom-metal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
block = "0.1"
core-graphics-types = "0.1"
libc = "0.2"
libloading = "0.8"
loom-core = { path = "../loom-core" }
loom-syntax = { path = "../loom-syntax" }
loom-validator = { path = "../loom-validator" }
metal = "0.29"
objc = "0.2"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
winit = "0.28"

[dev-dependencies]
loom-syntax = { path = "../loom-syntax" }

[[bin]]
name = "hello-particle-view"
path = "src/main.rs"
